server:
  port: 8082


spring:
  application:
    name: orders-api
  datasource:
    url: jdbc:h2:mem:orderentitydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orders-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#logging:
#  level:
#    org.springframework.kafka.listener: DEBUG
#    org.apache.kafka.clients.consumer: DEBUG


